---
- name: ensure go binary discoverable in PATH
  lineinfile:
    path: "{{ dotfile }}"
    state: present
    line: "[[ \":$PATH:\" != *\":/usr/lib/go-{{ go_version }}/bin:\"* ]] && PATH=\"/usr/lib/go-{{ go_version }}/bin:$PATH\" || true"
  when: ansible_os_family == 'Debian'

- name: ensure GOPATH directory exists
  file:
    path: "{{ gopath }}"
    state: directory

- name: set the GOPATH in the dotfile
  lineinfile:
    path: "{{ dotfile }}"
    state: present
    line: "export GOPATH={{ gopath }}"

- name: add GOPATH/bin to PATH
  lineinfile:
    path: "{{ dotfile }}"
    state: present
    line: "[[ \":$PATH:\" != *\":$GOPATH/bin:\"* ]] && PATH=\"$GOPATH/bin:$PATH\" || true"
    insertafter: "^export GOPATH"
