---
- name: install go packages
  shell: ". ~/.bashrc && go get -u {{ item }}"
  args:
    executable: /bin/bash
  with_items: "{{ go_bins }}"

- name: uninstall go packages
  shell: ". ~/.bashrc && go clean -i {{ item }}"
  args:
    executable: /bin/bash
  with_items: "{{ go_deleted_bins }}"
