---
- block:
  - name: add the gophers/archive ppa
    apt_repository:
      repo: "ppa:gophers/archive"
      state: present

  - name: install golang
    apt:
      package: "golang-{{ go_version }}-go"
      state: present
  become: yes
